### ISSUE TITLE
pf4j-update and pf4j spring issue

### ISSUE THREAD

**Issue by otmanel31** [pf4j/pf4j-spring#35]
Hi,

I try to use pf4j update with pf4j spring in my app ....
as describe in previous issue [https://github.com/pf4j/pf4j-spring/issues/31](url), i build locally the latest pf4j spring dependency.
I work with:
 - pf4j-spring 0.6.0-SNAPSHOT (that is in my local maven repo)
 - pf4j-update 2.1.0 (availble on official maven repo)
 - pf4j 3.0.1

When i try to get an updateManager using 
`
UpdateManager updateManager = new UpdateManager(pluginManager);`    and  i got an class not found execption as pluginException is not found. But all dependencies are correctly added. May be i forget something, but in previous issue, someone encountered a classNotFoundException (other class) and i would like to know if you are able to reproduce this issue.

Here logs about this exception: 

> 2019-07-24 19:21:43.518  INFO 9740 --- [           main] com.********.nx_plugin_in.InPlugin      : in plugin class successfully started
2019-07-24 19:21:43.694  INFO 9740 --- [           main] com.*********.demo.NxAgentApplication    : Started NxAgentApplication in 1.565 seconds (JVM running for 2.369)
2019-07-24 19:21:43.695  INFO 9740 --- [           main] com.*********.demo.NxAgentApplication    : in custom start ....
2019-07-24 19:21:43.735  INFO 9740 --- [           main] ConditionEvaluationReportLoggingListener :
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-07-24 19:21:43.741 ERROR 9740 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.NoClassDefFoundError: org/pf4j/PluginException
        at com.*********.demo.NxAgentApplication$1.run(NxAgentApplication.java:84) ~[classes!/:0.0.1-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
        at com.*********.demo.NxAgentApplication.main(NxAgentApplication.java:35) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_211]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [nx-agent-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) [nx-agent-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [nx-agent-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [nx-agent-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.ClassNotFoundException: org.pf4j.PluginException
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_211]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[nx-agent-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_211]
        ... 15 common frames omitted

**Comment by decebals** [comment]
Can you show us the fragment of your pom.xml (if you use Maven) where pf4j dependencies are declared?
Also please run `mvn dependency:tree` to see all the dependencies.

**Comment by otmanel31** [comment]
yes here my dependency tree:

> mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< com.********:nx-agent >-----------------------
[INFO] Building nx-agent 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ nx-agent ---
[INFO] com.********:nx-agent:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.1.6.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.1.6.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.6.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:compile
[INFO] |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.2:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.springframework:spring-core:jar:5.1.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.1.8.RELEASE:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.23:runtime
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.1.6.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.1.6.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.6.RELEASE:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.4:test
[INFO] |  +- junit:junit:jar:4.12:test
[INFO] |  +- org.assertj:assertj-core:jar:3.11.1:test
[INFO] |  +- org.mockito:mockito-core:jar:2.23.4:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.9.13:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.13:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.6:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.1.8.RELEASE:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.6.2:test
[INFO] +- org.pf4j:pf4j:jar:3.0.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.26:compile
[INFO] |  \- com.github.zafarkhaja:java-semver:jar:0.9.0:compile
[INFO] +- org.pf4j:pf4j-spring:jar:0.6.0-SNAPSHOT:compile
[INFO] |  \- org.springframework:spring-context:jar:5.1.8.RELEASE:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.1.8.RELEASE:compile
[INFO] |     +- org.springframework:spring-beans:jar:5.1.8.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.1.8.RELEASE:compile
[INFO] +- org.pf4j:pf4j-update:jar:2.1.0:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- log4j:log4j:jar:1.2.16:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.5:compile
[INFO] +- commons-lang:commons-lang:jar:2.4:compile
[INFO] \- com.********:nx-agent-api:jar:0.0.1-SNAPSHOT:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.957 s
[INFO] Finished at: 2019-07-25T09:42:28+02:00
[INFO] ------------------------------------------------------------------------

Then, my pom.xml dependencies section:

> 	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<version>2.1.6.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<version>2.1.6.RELEASE</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
		    <groupId>org.pf4j</groupId>
		    <artifactId>pf4j</artifactId>
		    <version>3.0.1</version>
		</dependency>
		<dependency>
		    <groupId>org.pf4j</groupId>
		    <artifactId>pf4j-spring</artifactId>
		    <version>0.6.0-SNAPSHOT</version>
		</dependency>		
		<dependency>
		    <groupId>org.pf4j</groupId>
		    <artifactId>pf4j-update</artifactId>
		    <version>2.1.0</version>
		</dependency>
		 
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.16</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.4</version>
        </dependency>
        
        <dependency>
	    	<groupId>com.***********</groupId>
	    	<artifactId>nx-agent-api</artifactId>
	    	<version>0.0.1-SNAPSHOT</version>
	    </dependency>
	</dependencies>

**Comment by decebals** [comment]
`org.pf4j.PluginException` doesn't exists anymore in PF4J 3.x. It was replaced by `PluginRuntimeException`. Can you check to see if you have a reference to this class (PluginException) in your plugins (start, stop, delete). Also please check if don't have a plugin at runtime (zip, jar) built for PF4J 2.x

**Comment by decebals** [comment]
I think that I found something in your `pom.xml`.
You use pf4j-update 2.1.0 that is not compatible with pf4j 3.x. Please use 2.2.0-SNAPSHOT for pf4j-update.

**Comment by otmanel31** [comment]
OK thanks ... this is a version/dependencies issues ... i'm able to start the update manager correctly in my app ... but i'm not able to found any new version in my folder repository to update my plugin ... but this is an other thing not related with this issue... may be i forgot something .... i close this issue... as resolve
